spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/feature_toggle?user=postgres&password=postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:/database/schema.sql
      data-locations: classpath:/database/data.sql
  jackson:
    deserialization:
      fail-on-unknown-properties: true
